import { Toaster } from "sonner";

import "./globals.css";
import Providers from "@/components/providers/Providers";

export const metadata = {
  metadataBase: new URL("https://redditpulse.solobuilder.com"),
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  maximumScale: 1, // Disable auto-zoom on mobile Safari
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
